### ISSUE TITLE
PHP7 Initialization issue

### ISSUE THREAD

**Issue by filt3rek** [HaxeFoundation/record-macros#31] opened 2018-11-23 12:09 UTC
Hej,

I get an error when I want to Serialize a relation on a SPOD object :
Uncaught ErrorException: Undefined property: user\User::$rights in /lib/Reflect.php:96
"rights" is a "relation" to UserRights class.
In the error output, I see Reflect.field is used, maybe it should do a Reflect.getProperty ?
But when I force Reflect.getProperty in the Manager instead of a Reflect.field, I get Memory Overflow.

Any ideas please ?

**Comment by filt3rek** [comment] 2018-11-23 12:15
Oh, it's my fault, the object was not initialized yet by SPOD when I wanted to serialize it.
Is there a way to avoid that behaviour please ? I had the same issues on PHP 5...

**Comment by filt3rek** [comment] 2018-11-23 12:37
I do that before all :

Manager.initialize();
Manager.cleanup();

**Comment by filt3rek** [comment] 2018-11-23 13:09
In my DB I have a session table and a userID relation to the user table. In Haxe I have a session and a user relation.
When I first get the session from the DB and I want just after that Serialize it, it fails with the error.
To avoid that, I have to explicitly get the right user from DB, User.manager.get( 2 ) even if I do nothing with that then It works fine, no errors.

**Comment by filt3rek** [comment] 2018-11-23 13:39
Ok, I have to set "lock" in my declaration to make it work :
```@:relation( userID, lock )
	public var user		: Null<User>;```
Can anybody explain me what's going on here please ?

**Comment by jonasmalacofilho** [comment] 2018-11-23 13:41
Can you share a minimal example?

**Comment by filt3rek** [comment] 2018-11-23 14:35
Hej Jonas,

Thanks for your answer.

I found my mistake, it was linked to @:relation( userID, lock )
But I can't understand how does it work, why I must explicitly add "lock" even if it's not a transaction :/

**Comment by jonasmalacofilho** [comment] 2018-11-23 14:53
I'm not sure, but I haven't fully understood what your code does.  That's why I asked for the minimal example.

**Comment by filt3rek** [comment] 2018-11-26 09:06
I have a session class/table like that :
```
@:table( "session" )
class Session extends Object {
	public var sid		: SString<32>;
	@:relation( userID, lock )
	public var user		: Null<User>;
}
```
So when first I get my session from the DB and I try to access my session's user's data, it fails if I don't add "lock" in @:relation.
And I wanted understand what it actually does to put "lock" in the relation meta. In the documentation it talks about transaction, but I don't use transactions here.

**Comment by bablukid** [comment] 2019-01-07 09:42
Hi @filt3rek 
record-macros is made to work with InnoDB transactions in MySQL ( https://dev.mysql.com/doc/refman/5.7/en/innodb-transaction-model.html )

Basically, using "lock" will lock the "user" record when you'll get it.
Locking a record means that nobody will be allowed to edit it until you release the lock ( at the transaction commit ).
It is translated in a "FOR UPDATE" statement in SQL.

ANyway, I don't know what happens when using this with no transactions...

**Comment by filt3rek** [comment] 2019-01-07 10:06
Hej François,

Happy new year, and thanks for your answer !

**Comment by jonasmalacofilho** [comment] 2019-03-22 08:32
Hi @filt3rek ,

I can't reproduce this...  Serializer does use `Reflect.field`, but that only causes the `@:relation` field to be null (not missing), and even that only _once the object is reconstructed._

Do you have a minimal (but complete) example?

---

```haxe
import haxe.Serializer;
import haxe.Unserializer;
import sys.db.*;
import sys.db.Types;

@:table("user")
class User extends Object {
	public var uid:SId;
	public var name:String;
}

@:table("session")
class Session extends Object {
	public var sid:SId;
	@:relation(user_id) public var user:Null<User>;
}

class Test {
	static function main()
	{
		Manager.initialize();
		Manager.cnx = Sqlite.open(":memory:");
		// Manager.cnx = Mysql.connect({...});
		TableCreate.create(User.manager);
		TableCreate.create(Session.manager);
		Manager.cleanup();

		var user = new User();
		user.name = "Random J User";
		user.insert();
		var session = new Session();
		session.user = user;
		session.insert();
		Manager.cleanup();

		session = Session.manager.all().first();

		var serial = Serializer.run(session);
		trace(serial);

		trace(session.user.name);

		var back = Unserializer.run(serial);
		trace(back);
		trace(back.user);  // null, not missing
		trace(back.user.name);  // fails just because back.user is null
	}
}
```

**Comment by filt3rek** [comment] 2019-03-22 09:32
Hej Jonas !

Thanks for your answer !
Well, I think this issue is linked to this one https://github.com/HaxeFoundation/record-macros/issues/34
Because if I set "lock" in the relation, it doesn't enter in the condition that delete the class fields.
BTW, I've commented hte fix you've done and I think It's still not good because we delete the class fields (or set it to null now with your fix) and then , we just repopulate the SPOD fields. The fields that are marked as "@:skip" are set to null :/

**Comment by jonasmalacofilho** [comment] 2019-03-22 09:56
> Well, I think this issue is linked to this one #34
> Because if I set "lock" in the relation, it doesn't enter in the condition that delete the class fields.

I had a similar suspicion.  I'm going to close this then.

**Closed by jonasmalacofilho** 2019-03-22 09:56 UTC
